// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/bober-17/meeting-room-booking-system/booking-service/internal/model"
)

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// DummyLogin provides a mock function with given fields: ctx, role
func (_m *MockAuthService) DummyLogin(ctx context.Context, role model.Role) (string, error) {
	ret := _m.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for DummyLogin")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Role) (string, error)); ok {
		return rf(ctx, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Role) string); ok {
		r0 = rf(ctx, role)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Role) error); ok {
		r1 = rf(ctx, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_DummyLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DummyLogin'
type MockAuthService_DummyLogin_Call struct {
	*mock.Call
}

// DummyLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - role model.Role
func (_e *MockAuthService_Expecter) DummyLogin(ctx interface{}, role interface{}) *MockAuthService_DummyLogin_Call {
	return &MockAuthService_DummyLogin_Call{Call: _e.mock.On("DummyLogin", ctx, role)}
}

func (_c *MockAuthService_DummyLogin_Call) Run(run func(ctx context.Context, role model.Role)) *MockAuthService_DummyLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Role))
	})
	return _c
}

func (_c *MockAuthService_DummyLogin_Call) Return(_a0 string, _a1 error) *MockAuthService_DummyLogin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_DummyLogin_Call) RunAndReturn(run func(context.Context, model.Role) (string, error)) *MockAuthService_DummyLogin_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, email, password
func (_m *MockAuthService) Login(ctx context.Context, email string, password string) (string, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockAuthService_Expecter) Login(ctx interface{}, email interface{}, password interface{}) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", ctx, email, password)}
}

func (_c *MockAuthService_Login_Call) Run(run func(ctx context.Context, email string, password string)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(_a0 string, _a1 error) *MockAuthService_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, email, password, role
func (_m *MockAuthService) Register(ctx context.Context, email string, password string, role model.Role) (model.User, error) {
	ret := _m.Called(ctx, email, password, role)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.Role) (model.User, error)); ok {
		return rf(ctx, email, password, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.Role) model.User); ok {
		r0 = rf(ctx, email, password, role)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, model.Role) error); ok {
		r1 = rf(ctx, email, password, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
//   - role model.Role
func (_e *MockAuthService_Expecter) Register(ctx interface{}, email interface{}, password interface{}, role interface{}) *MockAuthService_Register_Call {
	return &MockAuthService_Register_Call{Call: _e.mock.On("Register", ctx, email, password, role)}
}

func (_c *MockAuthService_Register_Call) Run(run func(ctx context.Context, email string, password string, role model.Role)) *MockAuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(model.Role))
	})
	return _c
}

func (_c *MockAuthService_Register_Call) Return(_a0 model.User, _a1 error) *MockAuthService_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_Register_Call) RunAndReturn(run func(context.Context, string, string, model.Role) (model.User, error)) *MockAuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
