// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/bober-17/meeting-room-booking-system/booking-service/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockBookingRepository is an autogenerated mock type for the BookingRepository type
type MockBookingRepository struct {
	mock.Mock
}

type MockBookingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingRepository) EXPECT() *MockBookingRepository_Expecter {
	return &MockBookingRepository_Expecter{mock: &_m.Mock}
}

// CancelBooking provides a mock function with given fields: ctx, id, userID
func (_m *MockBookingRepository) CancelBooking(ctx context.Context, id uuid.UUID, userID uuid.UUID) (model.Booking, error) {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for CancelBooking")
	}

	var r0 model.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (model.Booking, error)); ok {
		return rf(ctx, id, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) model.Booking); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Get(0).(model.Booking)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookingRepository_CancelBooking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelBooking'
type MockBookingRepository_CancelBooking_Call struct {
	*mock.Call
}

// CancelBooking is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockBookingRepository_Expecter) CancelBooking(ctx interface{}, id interface{}, userID interface{}) *MockBookingRepository_CancelBooking_Call {
	return &MockBookingRepository_CancelBooking_Call{Call: _e.mock.On("CancelBooking", ctx, id, userID)}
}

func (_c *MockBookingRepository_CancelBooking_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockBookingRepository_CancelBooking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockBookingRepository_CancelBooking_Call) Return(_a0 model.Booking, _a1 error) *MockBookingRepository_CancelBooking_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookingRepository_CancelBooking_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (model.Booking, error)) *MockBookingRepository_CancelBooking_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBooking provides a mock function with given fields: ctx, slotID, userID
func (_m *MockBookingRepository) CreateBooking(ctx context.Context, slotID uuid.UUID, userID uuid.UUID) (model.Booking, error) {
	ret := _m.Called(ctx, slotID, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateBooking")
	}

	var r0 model.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (model.Booking, error)); ok {
		return rf(ctx, slotID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) model.Booking); ok {
		r0 = rf(ctx, slotID, userID)
	} else {
		r0 = ret.Get(0).(model.Booking)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, slotID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookingRepository_CreateBooking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBooking'
type MockBookingRepository_CreateBooking_Call struct {
	*mock.Call
}

// CreateBooking is a helper method to define mock.On call
//   - ctx context.Context
//   - slotID uuid.UUID
//   - userID uuid.UUID
func (_e *MockBookingRepository_Expecter) CreateBooking(ctx interface{}, slotID interface{}, userID interface{}) *MockBookingRepository_CreateBooking_Call {
	return &MockBookingRepository_CreateBooking_Call{Call: _e.mock.On("CreateBooking", ctx, slotID, userID)}
}

func (_c *MockBookingRepository_CreateBooking_Call) Run(run func(ctx context.Context, slotID uuid.UUID, userID uuid.UUID)) *MockBookingRepository_CreateBooking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockBookingRepository_CreateBooking_Call) Return(_a0 model.Booking, _a1 error) *MockBookingRepository_CreateBooking_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookingRepository_CreateBooking_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (model.Booking, error)) *MockBookingRepository_CreateBooking_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookingByID provides a mock function with given fields: ctx, id
func (_m *MockBookingRepository) GetBookingByID(ctx context.Context, id uuid.UUID) (model.Booking, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingByID")
	}

	var r0 model.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Booking, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Booking); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Booking)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookingRepository_GetBookingByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookingByID'
type MockBookingRepository_GetBookingByID_Call struct {
	*mock.Call
}

// GetBookingByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockBookingRepository_Expecter) GetBookingByID(ctx interface{}, id interface{}) *MockBookingRepository_GetBookingByID_Call {
	return &MockBookingRepository_GetBookingByID_Call{Call: _e.mock.On("GetBookingByID", ctx, id)}
}

func (_c *MockBookingRepository_GetBookingByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockBookingRepository_GetBookingByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockBookingRepository_GetBookingByID_Call) Return(_a0 model.Booking, _a1 error) *MockBookingRepository_GetBookingByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookingRepository_GetBookingByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (model.Booking, error)) *MockBookingRepository_GetBookingByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListBookings provides a mock function with given fields: ctx, page, pageSize
func (_m *MockBookingRepository) ListBookings(ctx context.Context, page int, pageSize int) ([]model.Booking, int, error) {
	ret := _m.Called(ctx, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListBookings")
	}

	var r0 []model.Booking
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]model.Booking, int, error)); ok {
		return rf(ctx, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []model.Booking); ok {
		r0 = rf(ctx, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = rf(ctx, page, pageSize)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockBookingRepository_ListBookings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBookings'
type MockBookingRepository_ListBookings_Call struct {
	*mock.Call
}

// ListBookings is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - pageSize int
func (_e *MockBookingRepository_Expecter) ListBookings(ctx interface{}, page interface{}, pageSize interface{}) *MockBookingRepository_ListBookings_Call {
	return &MockBookingRepository_ListBookings_Call{Call: _e.mock.On("ListBookings", ctx, page, pageSize)}
}

func (_c *MockBookingRepository_ListBookings_Call) Run(run func(ctx context.Context, page int, pageSize int)) *MockBookingRepository_ListBookings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockBookingRepository_ListBookings_Call) Return(_a0 []model.Booking, _a1 int, _a2 error) *MockBookingRepository_ListBookings_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockBookingRepository_ListBookings_Call) RunAndReturn(run func(context.Context, int, int) ([]model.Booking, int, error)) *MockBookingRepository_ListBookings_Call {
	_c.Call.Return(run)
	return _c
}

// ListUserBookings provides a mock function with given fields: ctx, userID
func (_m *MockBookingRepository) ListUserBookings(ctx context.Context, userID uuid.UUID) ([]model.Booking, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListUserBookings")
	}

	var r0 []model.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.Booking, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.Booking); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookingRepository_ListUserBookings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserBookings'
type MockBookingRepository_ListUserBookings_Call struct {
	*mock.Call
}

// ListUserBookings is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockBookingRepository_Expecter) ListUserBookings(ctx interface{}, userID interface{}) *MockBookingRepository_ListUserBookings_Call {
	return &MockBookingRepository_ListUserBookings_Call{Call: _e.mock.On("ListUserBookings", ctx, userID)}
}

func (_c *MockBookingRepository_ListUserBookings_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockBookingRepository_ListUserBookings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockBookingRepository_ListUserBookings_Call) Return(_a0 []model.Booking, _a1 error) *MockBookingRepository_ListUserBookings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookingRepository_ListUserBookings_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]model.Booking, error)) *MockBookingRepository_ListUserBookings_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateConferenceLink provides a mock function with given fields: ctx, bookingID, link
func (_m *MockBookingRepository) UpdateConferenceLink(ctx context.Context, bookingID uuid.UUID, link string) error {
	ret := _m.Called(ctx, bookingID, link)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConferenceLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, bookingID, link)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBookingRepository_UpdateConferenceLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateConferenceLink'
type MockBookingRepository_UpdateConferenceLink_Call struct {
	*mock.Call
}

// UpdateConferenceLink is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID uuid.UUID
//   - link string
func (_e *MockBookingRepository_Expecter) UpdateConferenceLink(ctx interface{}, bookingID interface{}, link interface{}) *MockBookingRepository_UpdateConferenceLink_Call {
	return &MockBookingRepository_UpdateConferenceLink_Call{Call: _e.mock.On("UpdateConferenceLink", ctx, bookingID, link)}
}

func (_c *MockBookingRepository_UpdateConferenceLink_Call) Run(run func(ctx context.Context, bookingID uuid.UUID, link string)) *MockBookingRepository_UpdateConferenceLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockBookingRepository_UpdateConferenceLink_Call) Return(_a0 error) *MockBookingRepository_UpdateConferenceLink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBookingRepository_UpdateConferenceLink_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockBookingRepository_UpdateConferenceLink_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBookingRepository creates a new instance of MockBookingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingRepository {
	mock := &MockBookingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
