// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/bober-17/meeting-room-booking-system/booking-service/internal/model"

	time "time"

	uuid "github.com/google/uuid"
)

// MockSlotService is an autogenerated mock type for the SlotService type
type MockSlotService struct {
	mock.Mock
}

type MockSlotService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSlotService) EXPECT() *MockSlotService_Expecter {
	return &MockSlotService_Expecter{mock: &_m.Mock}
}

// ListAvailableSlots provides a mock function with given fields: ctx, roomID, date
func (_m *MockSlotService) ListAvailableSlots(ctx context.Context, roomID uuid.UUID, date time.Time) ([]model.Slot, error) {
	ret := _m.Called(ctx, roomID, date)

	if len(ret) == 0 {
		panic("no return value specified for ListAvailableSlots")
	}

	var r0 []model.Slot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) ([]model.Slot, error)); ok {
		return rf(ctx, roomID, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) []model.Slot); ok {
		r0 = rf(ctx, roomID, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Slot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, roomID, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSlotService_ListAvailableSlots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAvailableSlots'
type MockSlotService_ListAvailableSlots_Call struct {
	*mock.Call
}

// ListAvailableSlots is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - date time.Time
func (_e *MockSlotService_Expecter) ListAvailableSlots(ctx interface{}, roomID interface{}, date interface{}) *MockSlotService_ListAvailableSlots_Call {
	return &MockSlotService_ListAvailableSlots_Call{Call: _e.mock.On("ListAvailableSlots", ctx, roomID, date)}
}

func (_c *MockSlotService_ListAvailableSlots_Call) Run(run func(ctx context.Context, roomID uuid.UUID, date time.Time)) *MockSlotService_ListAvailableSlots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockSlotService_ListAvailableSlots_Call) Return(_a0 []model.Slot, _a1 error) *MockSlotService_ListAvailableSlots_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSlotService_ListAvailableSlots_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) ([]model.Slot, error)) *MockSlotService_ListAvailableSlots_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSlotService creates a new instance of MockSlotService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSlotService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSlotService {
	mock := &MockSlotService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
