// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/bober-17/meeting-room-booking-system/booking-service/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockBookingSlotRepository is an autogenerated mock type for the SlotRepository type
type MockBookingSlotRepository struct {
	mock.Mock
}

type MockBookingSlotRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingSlotRepository) EXPECT() *MockBookingSlotRepository_Expecter {
	return &MockBookingSlotRepository_Expecter{mock: &_m.Mock}
}

// GetSlotByID provides a mock function with given fields: ctx, id
func (_m *MockBookingSlotRepository) GetSlotByID(ctx context.Context, id uuid.UUID) (model.Slot, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSlotByID")
	}

	var r0 model.Slot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Slot, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Slot); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Slot)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookingSlotRepository_GetSlotByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSlotByID'
type MockBookingSlotRepository_GetSlotByID_Call struct {
	*mock.Call
}

// GetSlotByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockBookingSlotRepository_Expecter) GetSlotByID(ctx interface{}, id interface{}) *MockBookingSlotRepository_GetSlotByID_Call {
	return &MockBookingSlotRepository_GetSlotByID_Call{Call: _e.mock.On("GetSlotByID", ctx, id)}
}

func (_c *MockBookingSlotRepository_GetSlotByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockBookingSlotRepository_GetSlotByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockBookingSlotRepository_GetSlotByID_Call) Return(_a0 model.Slot, _a1 error) *MockBookingSlotRepository_GetSlotByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookingSlotRepository_GetSlotByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (model.Slot, error)) *MockBookingSlotRepository_GetSlotByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBookingSlotRepository creates a new instance of MockBookingSlotRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingSlotRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingSlotRepository {
	mock := &MockBookingSlotRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
