// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/internships-backend/test-backend-bober-17/internal/model"
)

// MockRoomService is an autogenerated mock type for the RoomService type
type MockRoomService struct {
	mock.Mock
}

type MockRoomService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoomService) EXPECT() *MockRoomService_Expecter {
	return &MockRoomService_Expecter{mock: &_m.Mock}
}

// CreateRoom provides a mock function with given fields: ctx, name, description, capacity
func (_m *MockRoomService) CreateRoom(ctx context.Context, name string, description *string, capacity *int) (model.Room, error) {
	ret := _m.Called(ctx, name, description, capacity)

	if len(ret) == 0 {
		panic("no return value specified for CreateRoom")
	}

	var r0 model.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, *int) (model.Room, error)); ok {
		return rf(ctx, name, description, capacity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, *int) model.Room); ok {
		r0 = rf(ctx, name, description, capacity)
	} else {
		r0 = ret.Get(0).(model.Room)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *string, *int) error); ok {
		r1 = rf(ctx, name, description, capacity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomService_CreateRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRoom'
type MockRoomService_CreateRoom_Call struct {
	*mock.Call
}

// CreateRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - description *string
//   - capacity *int
func (_e *MockRoomService_Expecter) CreateRoom(ctx interface{}, name interface{}, description interface{}, capacity interface{}) *MockRoomService_CreateRoom_Call {
	return &MockRoomService_CreateRoom_Call{Call: _e.mock.On("CreateRoom", ctx, name, description, capacity)}
}

func (_c *MockRoomService_CreateRoom_Call) Run(run func(ctx context.Context, name string, description *string, capacity *int)) *MockRoomService_CreateRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*string), args[3].(*int))
	})
	return _c
}

func (_c *MockRoomService_CreateRoom_Call) Return(_a0 model.Room, _a1 error) *MockRoomService_CreateRoom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomService_CreateRoom_Call) RunAndReturn(run func(context.Context, string, *string, *int) (model.Room, error)) *MockRoomService_CreateRoom_Call {
	_c.Call.Return(run)
	return _c
}

// ListRooms provides a mock function with given fields: ctx
func (_m *MockRoomService) ListRooms(ctx context.Context) ([]model.Room, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListRooms")
	}

	var r0 []model.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Room, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Room); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomService_ListRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRooms'
type MockRoomService_ListRooms_Call struct {
	*mock.Call
}

// ListRooms is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoomService_Expecter) ListRooms(ctx interface{}) *MockRoomService_ListRooms_Call {
	return &MockRoomService_ListRooms_Call{Call: _e.mock.On("ListRooms", ctx)}
}

func (_c *MockRoomService_ListRooms_Call) Run(run func(ctx context.Context)) *MockRoomService_ListRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRoomService_ListRooms_Call) Return(_a0 []model.Room, _a1 error) *MockRoomService_ListRooms_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomService_ListRooms_Call) RunAndReturn(run func(context.Context) ([]model.Room, error)) *MockRoomService_ListRooms_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoomService creates a new instance of MockRoomService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoomService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoomService {
	mock := &MockRoomService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
