// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/internships-backend/test-backend-bober-17/internal/model"

	uuid "github.com/google/uuid"
)

// MockScheduleService is an autogenerated mock type for the ScheduleService type
type MockScheduleService struct {
	mock.Mock
}

type MockScheduleService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScheduleService) EXPECT() *MockScheduleService_Expecter {
	return &MockScheduleService_Expecter{mock: &_m.Mock}
}

// CreateSchedule provides a mock function with given fields: ctx, roomID, daysOfWeek, startTime, endTime
func (_m *MockScheduleService) CreateSchedule(ctx context.Context, roomID uuid.UUID, daysOfWeek []int, startTime string, endTime string) (model.Schedule, error) {
	ret := _m.Called(ctx, roomID, daysOfWeek, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for CreateSchedule")
	}

	var r0 model.Schedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []int, string, string) (model.Schedule, error)); ok {
		return rf(ctx, roomID, daysOfWeek, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []int, string, string) model.Schedule); ok {
		r0 = rf(ctx, roomID, daysOfWeek, startTime, endTime)
	} else {
		r0 = ret.Get(0).(model.Schedule)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, []int, string, string) error); ok {
		r1 = rf(ctx, roomID, daysOfWeek, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockScheduleService_CreateSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSchedule'
type MockScheduleService_CreateSchedule_Call struct {
	*mock.Call
}

// CreateSchedule is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - daysOfWeek []int
//   - startTime string
//   - endTime string
func (_e *MockScheduleService_Expecter) CreateSchedule(ctx interface{}, roomID interface{}, daysOfWeek interface{}, startTime interface{}, endTime interface{}) *MockScheduleService_CreateSchedule_Call {
	return &MockScheduleService_CreateSchedule_Call{Call: _e.mock.On("CreateSchedule", ctx, roomID, daysOfWeek, startTime, endTime)}
}

func (_c *MockScheduleService_CreateSchedule_Call) Run(run func(ctx context.Context, roomID uuid.UUID, daysOfWeek []int, startTime string, endTime string)) *MockScheduleService_CreateSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]int), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockScheduleService_CreateSchedule_Call) Return(_a0 model.Schedule, _a1 error) *MockScheduleService_CreateSchedule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockScheduleService_CreateSchedule_Call) RunAndReturn(run func(context.Context, uuid.UUID, []int, string, string) (model.Schedule, error)) *MockScheduleService_CreateSchedule_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockScheduleService creates a new instance of MockScheduleService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScheduleService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScheduleService {
	mock := &MockScheduleService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
