// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockConferenceClient is an autogenerated mock type for the ConferenceClient type
type MockConferenceClient struct {
	mock.Mock
}

type MockConferenceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConferenceClient) EXPECT() *MockConferenceClient_Expecter {
	return &MockConferenceClient_Expecter{mock: &_m.Mock}
}

// CreateLink provides a mock function with given fields: ctx, bookingID
func (_m *MockConferenceClient) CreateLink(ctx context.Context, bookingID uuid.UUID) (string, error) {
	ret := _m.Called(ctx, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for CreateLink")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (string, error)); ok {
		return rf(ctx, bookingID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) string); ok {
		r0 = rf(ctx, bookingID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, bookingID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConferenceClient_CreateLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLink'
type MockConferenceClient_CreateLink_Call struct {
	*mock.Call
}

// CreateLink is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID uuid.UUID
func (_e *MockConferenceClient_Expecter) CreateLink(ctx interface{}, bookingID interface{}) *MockConferenceClient_CreateLink_Call {
	return &MockConferenceClient_CreateLink_Call{Call: _e.mock.On("CreateLink", ctx, bookingID)}
}

func (_c *MockConferenceClient_CreateLink_Call) Run(run func(ctx context.Context, bookingID uuid.UUID)) *MockConferenceClient_CreateLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockConferenceClient_CreateLink_Call) Return(_a0 string, _a1 error) *MockConferenceClient_CreateLink_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConferenceClient_CreateLink_Call) RunAndReturn(run func(context.Context, uuid.UUID) (string, error)) *MockConferenceClient_CreateLink_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConferenceClient creates a new instance of MockConferenceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConferenceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConferenceClient {
	mock := &MockConferenceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
