// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockSlotRoomRepository is an autogenerated mock type for the RoomRepository type
type MockSlotRoomRepository struct {
	mock.Mock
}

type MockSlotRoomRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSlotRoomRepository) EXPECT() *MockSlotRoomRepository_Expecter {
	return &MockSlotRoomRepository_Expecter{mock: &_m.Mock}
}

// RoomExists provides a mock function with given fields: ctx, roomID
func (_m *MockSlotRoomRepository) RoomExists(ctx context.Context, roomID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for RoomExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return rf(ctx, roomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = rf(ctx, roomID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSlotRoomRepository_RoomExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RoomExists'
type MockSlotRoomRepository_RoomExists_Call struct {
	*mock.Call
}

// RoomExists is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
func (_e *MockSlotRoomRepository_Expecter) RoomExists(ctx interface{}, roomID interface{}) *MockSlotRoomRepository_RoomExists_Call {
	return &MockSlotRoomRepository_RoomExists_Call{Call: _e.mock.On("RoomExists", ctx, roomID)}
}

func (_c *MockSlotRoomRepository_RoomExists_Call) Run(run func(ctx context.Context, roomID uuid.UUID)) *MockSlotRoomRepository_RoomExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSlotRoomRepository_RoomExists_Call) Return(_a0 bool, _a1 error) *MockSlotRoomRepository_RoomExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSlotRoomRepository_RoomExists_Call) RunAndReturn(run func(context.Context, uuid.UUID) (bool, error)) *MockSlotRoomRepository_RoomExists_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSlotRoomRepository creates a new instance of MockSlotRoomRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSlotRoomRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSlotRoomRepository {
	mock := &MockSlotRoomRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
