// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/internships-backend/test-backend-bober-17/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockSlotScheduleRepository is an autogenerated mock type for the ScheduleRepository type
type MockSlotScheduleRepository struct {
	mock.Mock
}

type MockSlotScheduleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSlotScheduleRepository) EXPECT() *MockSlotScheduleRepository_Expecter {
	return &MockSlotScheduleRepository_Expecter{mock: &_m.Mock}
}

// GetScheduleByRoomID provides a mock function with given fields: ctx, roomID
func (_m *MockSlotScheduleRepository) GetScheduleByRoomID(ctx context.Context, roomID uuid.UUID) (model.Schedule, error) {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetScheduleByRoomID")
	}

	var r0 model.Schedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Schedule, error)); ok {
		return rf(ctx, roomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Schedule); ok {
		r0 = rf(ctx, roomID)
	} else {
		r0 = ret.Get(0).(model.Schedule)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSlotScheduleRepository_GetScheduleByRoomID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScheduleByRoomID'
type MockSlotScheduleRepository_GetScheduleByRoomID_Call struct {
	*mock.Call
}

// GetScheduleByRoomID is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
func (_e *MockSlotScheduleRepository_Expecter) GetScheduleByRoomID(ctx interface{}, roomID interface{}) *MockSlotScheduleRepository_GetScheduleByRoomID_Call {
	return &MockSlotScheduleRepository_GetScheduleByRoomID_Call{Call: _e.mock.On("GetScheduleByRoomID", ctx, roomID)}
}

func (_c *MockSlotScheduleRepository_GetScheduleByRoomID_Call) Run(run func(ctx context.Context, roomID uuid.UUID)) *MockSlotScheduleRepository_GetScheduleByRoomID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSlotScheduleRepository_GetScheduleByRoomID_Call) Return(_a0 model.Schedule, _a1 error) *MockSlotScheduleRepository_GetScheduleByRoomID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSlotScheduleRepository_GetScheduleByRoomID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (model.Schedule, error)) *MockSlotScheduleRepository_GetScheduleByRoomID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSlotScheduleRepository creates a new instance of MockSlotScheduleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSlotScheduleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSlotScheduleRepository {
	mock := &MockSlotScheduleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
