// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/internships-backend/test-backend-bober-17/internal/model"

	uuid "github.com/google/uuid"
)

// MockBookingService is an autogenerated mock type for the BookingService type
type MockBookingService struct {
	mock.Mock
}

type MockBookingService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingService) EXPECT() *MockBookingService_Expecter {
	return &MockBookingService_Expecter{mock: &_m.Mock}
}

// CancelBooking provides a mock function with given fields: ctx, bookingID, userID
func (_m *MockBookingService) CancelBooking(ctx context.Context, bookingID uuid.UUID, userID uuid.UUID) (model.Booking, error) {
	ret := _m.Called(ctx, bookingID, userID)

	if len(ret) == 0 {
		panic("no return value specified for CancelBooking")
	}

	var r0 model.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (model.Booking, error)); ok {
		return rf(ctx, bookingID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) model.Booking); ok {
		r0 = rf(ctx, bookingID, userID)
	} else {
		r0 = ret.Get(0).(model.Booking)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, bookingID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookingService_CancelBooking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelBooking'
type MockBookingService_CancelBooking_Call struct {
	*mock.Call
}

// CancelBooking is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID uuid.UUID
//   - userID uuid.UUID
func (_e *MockBookingService_Expecter) CancelBooking(ctx interface{}, bookingID interface{}, userID interface{}) *MockBookingService_CancelBooking_Call {
	return &MockBookingService_CancelBooking_Call{Call: _e.mock.On("CancelBooking", ctx, bookingID, userID)}
}

func (_c *MockBookingService_CancelBooking_Call) Run(run func(ctx context.Context, bookingID uuid.UUID, userID uuid.UUID)) *MockBookingService_CancelBooking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockBookingService_CancelBooking_Call) Return(_a0 model.Booking, _a1 error) *MockBookingService_CancelBooking_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookingService_CancelBooking_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (model.Booking, error)) *MockBookingService_CancelBooking_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBooking provides a mock function with given fields: ctx, slotID, userID, createConferenceLink
func (_m *MockBookingService) CreateBooking(ctx context.Context, slotID uuid.UUID, userID uuid.UUID, createConferenceLink bool) (model.Booking, error) {
	ret := _m.Called(ctx, slotID, userID, createConferenceLink)

	if len(ret) == 0 {
		panic("no return value specified for CreateBooking")
	}

	var r0 model.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, bool) (model.Booking, error)); ok {
		return rf(ctx, slotID, userID, createConferenceLink)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, bool) model.Booking); ok {
		r0 = rf(ctx, slotID, userID, createConferenceLink)
	} else {
		r0 = ret.Get(0).(model.Booking)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, bool) error); ok {
		r1 = rf(ctx, slotID, userID, createConferenceLink)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookingService_CreateBooking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBooking'
type MockBookingService_CreateBooking_Call struct {
	*mock.Call
}

// CreateBooking is a helper method to define mock.On call
//   - ctx context.Context
//   - slotID uuid.UUID
//   - userID uuid.UUID
//   - createConferenceLink bool
func (_e *MockBookingService_Expecter) CreateBooking(ctx interface{}, slotID interface{}, userID interface{}, createConferenceLink interface{}) *MockBookingService_CreateBooking_Call {
	return &MockBookingService_CreateBooking_Call{Call: _e.mock.On("CreateBooking", ctx, slotID, userID, createConferenceLink)}
}

func (_c *MockBookingService_CreateBooking_Call) Run(run func(ctx context.Context, slotID uuid.UUID, userID uuid.UUID, createConferenceLink bool)) *MockBookingService_CreateBooking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(bool))
	})
	return _c
}

func (_c *MockBookingService_CreateBooking_Call) Return(_a0 model.Booking, _a1 error) *MockBookingService_CreateBooking_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookingService_CreateBooking_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, bool) (model.Booking, error)) *MockBookingService_CreateBooking_Call {
	_c.Call.Return(run)
	return _c
}

// ListBookings provides a mock function with given fields: ctx, page, pageSize
func (_m *MockBookingService) ListBookings(ctx context.Context, page int, pageSize int) ([]model.Booking, int, error) {
	ret := _m.Called(ctx, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListBookings")
	}

	var r0 []model.Booking
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]model.Booking, int, error)); ok {
		return rf(ctx, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []model.Booking); ok {
		r0 = rf(ctx, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = rf(ctx, page, pageSize)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockBookingService_ListBookings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBookings'
type MockBookingService_ListBookings_Call struct {
	*mock.Call
}

// ListBookings is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - pageSize int
func (_e *MockBookingService_Expecter) ListBookings(ctx interface{}, page interface{}, pageSize interface{}) *MockBookingService_ListBookings_Call {
	return &MockBookingService_ListBookings_Call{Call: _e.mock.On("ListBookings", ctx, page, pageSize)}
}

func (_c *MockBookingService_ListBookings_Call) Run(run func(ctx context.Context, page int, pageSize int)) *MockBookingService_ListBookings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockBookingService_ListBookings_Call) Return(_a0 []model.Booking, _a1 int, _a2 error) *MockBookingService_ListBookings_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockBookingService_ListBookings_Call) RunAndReturn(run func(context.Context, int, int) ([]model.Booking, int, error)) *MockBookingService_ListBookings_Call {
	_c.Call.Return(run)
	return _c
}

// ListUserBookings provides a mock function with given fields: ctx, userID
func (_m *MockBookingService) ListUserBookings(ctx context.Context, userID uuid.UUID) ([]model.Booking, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListUserBookings")
	}

	var r0 []model.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.Booking, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.Booking); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookingService_ListUserBookings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserBookings'
type MockBookingService_ListUserBookings_Call struct {
	*mock.Call
}

// ListUserBookings is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockBookingService_Expecter) ListUserBookings(ctx interface{}, userID interface{}) *MockBookingService_ListUserBookings_Call {
	return &MockBookingService_ListUserBookings_Call{Call: _e.mock.On("ListUserBookings", ctx, userID)}
}

func (_c *MockBookingService_ListUserBookings_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockBookingService_ListUserBookings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockBookingService_ListUserBookings_Call) Return(_a0 []model.Booking, _a1 error) *MockBookingService_ListUserBookings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookingService_ListUserBookings_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]model.Booking, error)) *MockBookingService_ListUserBookings_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBookingService creates a new instance of MockBookingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingService {
	mock := &MockBookingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
