// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/internships-backend/test-backend-bober-17/internal/model"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockSlotRepository is an autogenerated mock type for the SlotRepository type
type MockSlotRepository struct {
	mock.Mock
}

type MockSlotRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSlotRepository) EXPECT() *MockSlotRepository_Expecter {
	return &MockSlotRepository_Expecter{mock: &_m.Mock}
}

// EnsureSlots provides a mock function with given fields: ctx, slots
func (_m *MockSlotRepository) EnsureSlots(ctx context.Context, slots []model.Slot) error {
	ret := _m.Called(ctx, slots)

	if len(ret) == 0 {
		panic("no return value specified for EnsureSlots")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []model.Slot) error); ok {
		r0 = rf(ctx, slots)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSlotRepository_EnsureSlots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureSlots'
type MockSlotRepository_EnsureSlots_Call struct {
	*mock.Call
}

// EnsureSlots is a helper method to define mock.On call
//   - ctx context.Context
//   - slots []model.Slot
func (_e *MockSlotRepository_Expecter) EnsureSlots(ctx interface{}, slots interface{}) *MockSlotRepository_EnsureSlots_Call {
	return &MockSlotRepository_EnsureSlots_Call{Call: _e.mock.On("EnsureSlots", ctx, slots)}
}

func (_c *MockSlotRepository_EnsureSlots_Call) Run(run func(ctx context.Context, slots []model.Slot)) *MockSlotRepository_EnsureSlots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]model.Slot))
	})
	return _c
}

func (_c *MockSlotRepository_EnsureSlots_Call) Return(_a0 error) *MockSlotRepository_EnsureSlots_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSlotRepository_EnsureSlots_Call) RunAndReturn(run func(context.Context, []model.Slot) error) *MockSlotRepository_EnsureSlots_Call {
	_c.Call.Return(run)
	return _c
}

// ListAvailableByRoomAndDate provides a mock function with given fields: ctx, roomID, from, to
func (_m *MockSlotRepository) ListAvailableByRoomAndDate(ctx context.Context, roomID uuid.UUID, from time.Time, to time.Time) ([]model.Slot, error) {
	ret := _m.Called(ctx, roomID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for ListAvailableByRoomAndDate")
	}

	var r0 []model.Slot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) ([]model.Slot, error)); ok {
		return rf(ctx, roomID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) []model.Slot); ok {
		r0 = rf(ctx, roomID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Slot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(ctx, roomID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSlotRepository_ListAvailableByRoomAndDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAvailableByRoomAndDate'
type MockSlotRepository_ListAvailableByRoomAndDate_Call struct {
	*mock.Call
}

// ListAvailableByRoomAndDate is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - from time.Time
//   - to time.Time
func (_e *MockSlotRepository_Expecter) ListAvailableByRoomAndDate(ctx interface{}, roomID interface{}, from interface{}, to interface{}) *MockSlotRepository_ListAvailableByRoomAndDate_Call {
	return &MockSlotRepository_ListAvailableByRoomAndDate_Call{Call: _e.mock.On("ListAvailableByRoomAndDate", ctx, roomID, from, to)}
}

func (_c *MockSlotRepository_ListAvailableByRoomAndDate_Call) Run(run func(ctx context.Context, roomID uuid.UUID, from time.Time, to time.Time)) *MockSlotRepository_ListAvailableByRoomAndDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockSlotRepository_ListAvailableByRoomAndDate_Call) Return(_a0 []model.Slot, _a1 error) *MockSlotRepository_ListAvailableByRoomAndDate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSlotRepository_ListAvailableByRoomAndDate_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time, time.Time) ([]model.Slot, error)) *MockSlotRepository_ListAvailableByRoomAndDate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSlotRepository creates a new instance of MockSlotRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSlotRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSlotRepository {
	mock := &MockSlotRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
