// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/bober-17/meeting-room-booking-system/notification-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, n
func (_m *MockRepository) Create(ctx context.Context, n model.Notification) (bool, error) {
	ret := _m.Called(ctx, n)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Notification) (bool, error)); ok {
		return rf(ctx, n)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Notification) bool); ok {
		r0 = rf(ctx, n)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Notification) error); ok {
		r1 = rf(ctx, n)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - n model.Notification
func (_e *MockRepository_Expecter) Create(ctx interface{}, n interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, n)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, n model.Notification)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Notification))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 bool, _a1 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context.Context, model.Notification) (bool, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function with given fields: ctx, userID, limit, offset, unreadOnly
func (_m *MockRepository) ListByUserID(ctx context.Context, userID string, limit int, offset int, unreadOnly bool) ([]model.Notification, int, error) {
	ret := _m.Called(ctx, userID, limit, offset, unreadOnly)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []model.Notification
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, bool) ([]model.Notification, int, error)); ok {
		return rf(ctx, userID, limit, offset, unreadOnly)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, bool) []model.Notification); ok {
		r0 = rf(ctx, userID, limit, offset, unreadOnly)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int, bool) int); ok {
		r1 = rf(ctx, userID, limit, offset, unreadOnly)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int, bool) error); ok {
		r2 = rf(ctx, userID, limit, offset, unreadOnly)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepository_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockRepository_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - limit int
//   - offset int
//   - unreadOnly bool
func (_e *MockRepository_Expecter) ListByUserID(ctx interface{}, userID interface{}, limit interface{}, offset interface{}, unreadOnly interface{}) *MockRepository_ListByUserID_Call {
	return &MockRepository_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID, limit, offset, unreadOnly)}
}

func (_c *MockRepository_ListByUserID_Call) Run(run func(ctx context.Context, userID string, limit int, offset int, unreadOnly bool)) *MockRepository_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int), args[4].(bool))
	})
	return _c
}

func (_c *MockRepository_ListByUserID_Call) Return(_a0 []model.Notification, _a1 int, _a2 error) *MockRepository_ListByUserID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRepository_ListByUserID_Call) RunAndReturn(run func(context.Context, string, int, int, bool) ([]model.Notification, int, error)) *MockRepository_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAllAsRead provides a mock function with given fields: ctx, userID
func (_m *MockRepository) MarkAllAsRead(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAllAsRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_MarkAllAsRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAllAsRead'
type MockRepository_MarkAllAsRead_Call struct {
	*mock.Call
}

// MarkAllAsRead is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepository_Expecter) MarkAllAsRead(ctx interface{}, userID interface{}) *MockRepository_MarkAllAsRead_Call {
	return &MockRepository_MarkAllAsRead_Call{Call: _e.mock.On("MarkAllAsRead", ctx, userID)}
}

func (_c *MockRepository_MarkAllAsRead_Call) Run(run func(ctx context.Context, userID string)) *MockRepository_MarkAllAsRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_MarkAllAsRead_Call) Return(_a0 error) *MockRepository_MarkAllAsRead_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_MarkAllAsRead_Call) RunAndReturn(run func(context.Context, string) error) *MockRepository_MarkAllAsRead_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAsRead provides a mock function with given fields: ctx, id, userID
func (_m *MockRepository) MarkAsRead(ctx context.Context, id string, userID string) error {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAsRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_MarkAsRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAsRead'
type MockRepository_MarkAsRead_Call struct {
	*mock.Call
}

// MarkAsRead is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *MockRepository_Expecter) MarkAsRead(ctx interface{}, id interface{}, userID interface{}) *MockRepository_MarkAsRead_Call {
	return &MockRepository_MarkAsRead_Call{Call: _e.mock.On("MarkAsRead", ctx, id, userID)}
}

func (_c *MockRepository_MarkAsRead_Call) Run(run func(ctx context.Context, id string, userID string)) *MockRepository_MarkAsRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_MarkAsRead_Call) Return(_a0 error) *MockRepository_MarkAsRead_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_MarkAsRead_Call) RunAndReturn(run func(context.Context, string, string) error) *MockRepository_MarkAsRead_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
