// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "github.com/bober-17/meeting-room-booking-system/notification-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockHub is an autogenerated mock type for the Hub type
type MockHub struct {
	mock.Mock
}

type MockHub_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHub) EXPECT() *MockHub_Expecter {
	return &MockHub_Expecter{mock: &_m.Mock}
}

// Broadcast provides a mock function with given fields: userID, n
func (_m *MockHub) Broadcast(userID string, n model.Notification) {
	_m.Called(userID, n)
}

// MockHub_Broadcast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Broadcast'
type MockHub_Broadcast_Call struct {
	*mock.Call
}

// Broadcast is a helper method to define mock.On call
//   - userID string
//   - n model.Notification
func (_e *MockHub_Expecter) Broadcast(userID interface{}, n interface{}) *MockHub_Broadcast_Call {
	return &MockHub_Broadcast_Call{Call: _e.mock.On("Broadcast", userID, n)}
}

func (_c *MockHub_Broadcast_Call) Run(run func(userID string, n model.Notification)) *MockHub_Broadcast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(model.Notification))
	})
	return _c
}

func (_c *MockHub_Broadcast_Call) Return() *MockHub_Broadcast_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHub_Broadcast_Call) RunAndReturn(run func(string, model.Notification)) *MockHub_Broadcast_Call {
	_c.Run(run)
	return _c
}

// NewMockHub creates a new instance of MockHub. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHub(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHub {
	mock := &MockHub{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
